surfnet_stepup_u2f.service.registration:
    class: Surfnet\StepupU2fBundle\Service\RegistrationService
    arguments:
        - @surfnet_stepup_u2f.yubico.u2f

surfnet_stepup_u2f.service.authentication:
    class: Surfnet\StepupU2fBundle\Service\AuthenticationVerificationService
    arguments:
        - @surfnet_stepup_u2f.yubico.u2f

surfnet_stepup_u2f.yubico.u2f:
    class: u2flib_server\U2F
    arguments:
        - ''   # AppID is configured
        - null # No directory with attestation certs

surfnet_stepup_u2f.form.register_device:
    class: Surfnet\StepupU2fBundle\Form\Type\RegisterDeviceType
    tags: [{ name: form.type, alias: surfnet_stepup_u2f_register_device }]
