services:
    # Remove the public: true default once DI is implemented throughout the StepUp applications. See Pivotal #138225085
    _defaults:
        public: true

    surfnet_stepup_u2f.value.app_id:
        public: false
        class: Surfnet\StepupU2fBundle\Value\AppId
        arguments:
             - '' # AppID is configured

    surfnet_stepup_u2f.service.u2f:
        class: Surfnet\StepupU2fBundle\Service\U2fService
        arguments:
            - "@surfnet_stepup_u2f.value.app_id"
            - "@surfnet_stepup_u2f.yubico.u2f"

    surfnet_stepup_u2f.yubico.u2f:
        class: u2flib_server\U2F
        arguments:
            - ''   # AppID is configured
            - null # No directory with attestation certs

    surfnet_stepup_u2f.form.register_device:
        class: Surfnet\StepupU2fBundle\Form\Type\RegisterDeviceType
        tags: [{ name: form.type, alias: surfnet_stepup_u2f_register_device }]

    surfnet_stepup_u2f.form.verify_device_authentication:
        class: Surfnet\StepupU2fBundle\Form\Type\VerifyDeviceAuthenticationType
        tags: [{ name: form.type, alias: surfnet_stepup_u2f_verify_device_authentication }]
